import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import {Stack} from "@mui/material";

const BaseLayout = ({children, title}) => {
  return (
    <>
      <Header>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Header>
      <Navbar/>
      <Stack sx={{minHeight: '80vh'}}>
        {children}
      </Stack>
      <Footer/>
    </>
  )
}

export default BaseLayout;